### ISSUE TITLE
在 VMWare 虚拟机上发生 panic: runtime error: invalid memory address or nil pointer dereference 错误

### ISSUE THREAD

**Issue by CHN-STUDENT** [CHN-STUDENT/ServerStatus#3]
系统信息
```
主机名:           WIN-5UTOBMTO767
OS 名称:          Microsoft Windows Server 2012 R2 Standard
OS 版本:          6.3.9600 暂缺 Build 9600
OS 制造商:        Microsoft Corporation
OS 配置:          独立服务器
OS 构件类型:      Multiprocessor Free
注册的所有人:     Windows 用户
注册的组织:       
产品 ID:          00252-70000-00000-AA535
初始安装日期:     2020/11/4, 8:15:34
系统启动时间:     2020/11/10, 17:01:32
系统制造商:       VMware, Inc.
系统型号:         VMware Virtual Platform
系统类型:         x64-based PC
处理器:           安装了 2 个处理器。
                  [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~2200 Mhz
                  [02]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~2200 Mhz
BIOS 版本:        Phoenix Technologies LTD 6.00, 2015/9/21
Windows 目录:     C:\Windows
系统目录:         C:\Windows\system32
启动设备:         \Device\HarddiskVolume1
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00)北京，重庆，香港特别行政区，乌鲁木齐
物理内存总量:     32,768 MB
可用的物理内存:   28,102 MB
虚拟内存: 最大值: 37,632 MB
虚拟内存: 可用:   32,339 MB
虚拟内存: 使用中: 5,293 MB
页面文件位置:     C:\pagefile.sys
域:               WORKGROUP
登录服务器:       \\WIN-5UTOBMTO767
修补程序:         安装了 20 个修补程序。
                  [01]: KB2862152
                  [02]: KB2868626
                  [03]: KB2876331
                  [04]: KB2883200
                  [05]: KB2884101
                  [06]: KB2884846
                  [07]: KB2887595
                  [08]: KB2888505
                  [09]: KB2894029
                  [10]: KB2894179
                  [11]: KB2898514
                  [12]: KB2900986
                  [13]: KB2901101
                  [14]: KB2906956
                  [15]: KB2908174
                  [16]: KB2919355
                  [17]: KB2919442
                  [18]: KB2959977
                  [19]: KB2999226
                  [20]: KB3151864
网卡:             安装了 1 个 NIC。
                  [01]: Intel(R) 82574L 千兆网络连接
                      连接名:      Ethernet0
                      启用 DHCP:   否
                      IP 地址
                        [01]: 172.16.172.229
                        [02]: fe80::bd27:8296:aa65:edf2
Hyper-V 要求:     已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。
```

控制台输出
``` 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6ae544]

goroutine 7 [running]:
main.(*PingValue).RunCU.func1(0xc000005aa0)
        C:/Users/Administrator/Desktop/awesomeProject/ping.go:42 +0x204
created by main.(*PingValue).RunCU
        C:/Users/Administrator/Desktop/awesomeProject/ping.go:26 +0x46
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6aefc4]

goroutine 9 [running]:
main.(*PingValue).RunCM.func1(0xc000005ae0)
        C:/Users/Administrator/Desktop/awesomeProject/ping.go:130 +0x204
created by main.(*PingValue).RunCM
        C:/Users/Administrator/Desktop/awesomeProject/ping.go:114 +0x46
```

**Comment by CHN-STUDENT** [comment]
修改程序使用 linux 运行输出
```
[root@reg awesomeProject]# ./start.sh 
Authentication successful. Access granted.

Authentication successful. Access granted.

You are connecting via: IPv4

6
Error try to connect China unicom : dial tcp 120.52.99.224:80: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6a770b]

goroutine 9 [running]:
main.(*PingValue).RunCU.func1(0xc00000ef40)
	/root/ServerStatus/clients/awesomeProject/ping.go:45 +0x28b
created by main.(*PingValue).RunCU
	/root/ServerStatus/clients/awesomeProject/ping.go:26 +0x3f
您在 /var/spool/mail/root 中有新邮件

```
